CREATE TABLE IF NOT EXISTS DEPARTMENT(
    E_ID TEXT,
    NAME TEXT,
    D_ID TEXT,
    M_ID TEXT,
    SALARY REAL
);

INSERT INTO DEPARTMENT(E_ID, NAME, D_ID, M_ID, SALARY)
VALUES 
    ('100', 'JOHN', '180', '182', 99999999),
    ('101', 'JOE', '181', '183', 88888888),
    ('102', 'JONES', '182', '184', 77777777),
    ('103', 'JAMES', '183', '185', 66666666),
    ('104', 'JONY', '184', '186', 55555555);

SELECT D_ID AS "DEPARTMENT CODE",
COUNT(*) AS "NUMBER OF EMPLOYEE" 
FROM DEPARTMENT 
GROUP BY D_ID;

SELECT D_ID, SUM(SALARY) 
FROM DEPARTMENT 
GROUP BY D_ID;

SELECT D_ID AS "DEPARTMENT CODE",
COUNT(*) AS "NUMBER OF EMPLOYEE",
SUM(SALARY) AS "TOTAL SALARY" 
FROM DEPARTMENT 
GROUP BY D_ID;

SELECT D_ID AS "DEPARTMENT CODE",
SUM(SALARY) AS "TOTAL SALARY" 
FROM DEPARTMENT 
WHERE M_ID = '184' 
GROUP BY D_ID;

SELECT D_ID, 
COUNT(*) AS "NUMBER OF EMPLOYEE" 
FROM DEPARTMENT 
GROUP BY D_ID 
HAVING COUNT(*) > 2;
